[package]
name = "vl53l5"
version = "0.1.0"
edition = "2021"

[dependencies]
c2rust-bitfields = { version = "0.19.0", features = ["no_std"] }

[dev-dependencies]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", package = "esp-hal", rev = "feaf66847cf6b8c9a8d43a10bbbf563853c2e39b", features = [
    "esp32c3",
] }
esp-println = { version = "0.11.0", features = ["esp32c3", "log"] }
esp-backtrace = { version = "0.14.1", features = [
    "esp32c3",
    "exception-handler",
    "panic-handler",
    "println",
] }
critical-section = "1.1.3"
embedded-hal = "1.0.0"
log = { version = "0.4.22" }
