[package]
name = "vl53l5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2rust-bitfields = { version = "0.19.0", features = ["no_std"] }


esp-hal = { path = "/projects/esp/esp-hal/esp-hal", features = ["esp32c3"] }
esp-println = { path = "/projects/esp/esp-hal/esp-println", features = ["esp32c3", "log"] }
esp-backtrace = { path = "/projects/esp/esp-hal/esp-backtrace", features = [
    "esp32c3",
    "exception-handler",
    "panic-handler",
    "println",
] }
critical-section = "1.1.3"

log = { version = "0.4.22" }
